### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by MateuszFlisikowski** [atom/image-view#108]
You have the core package "image-view" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (C:\Users\mateusz\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\dalek\lib\main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (C:\Users\mateusz\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
Emitter.emit (C:\Users\mateusz\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:141:28)
<unknown> (C:\Users\mateusz\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:514:32)
```

**Comment by rsese** [comment]
See the error message for details on how to resolve this problem:

> You have the core package "go-to-line" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.

Also see my comment here /cc https://github.com/atom/go-to-line/issues/45#issuecomment-300606253.
