### ISSUE TITLE
Zoom steps are changing

### ISSUE THREAD

**Issue by TimvdLippe** [atom/image-view#123]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using the zoom in and out buttons, the zoom levels it moves to are inconsistent. Zooming out after zooming in ends up at a different percentage.

### Steps to Reproduce

1. Open image
2. Zoom in twice, zoom out once

**Expected behavior:** Image is zoomed at 125-150-125%

**Actual behavior:** Image is zoomed in at 125-156-117%, 

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
tim$ atom --version
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
tim$ apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.13.0
```
Ubuntu 16.04

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Looks like it's doing `existing_percentage * 1.25` rather than `existing_percentage + 0.25`.
