### ISSUE TITLE
[Enhancement] Show the Image Dimensions

### ISSUE THREAD

**Issue by blairanderson** [atom/image-view#168]
If this image-viewer is the default, i would like to submit a pull request to display the image dimensions somewhere on the screen when an image is being viewed. 

given that image dimensions are helpful for loading images quickly, and for accessibility, image dimensions are important. 

Am creating an issue to ask: "**will someone review a PR if i submit it?**"

**Comment by Ben3eeE** [comment]
The image-view should already show dimensions in pixels and file size in the status bar:

![image](https://user-images.githubusercontent.com/1058982/35113079-8d710b30-fc80-11e7-9abc-676dd15dd436.png)

Is this not working for you or is there another dimension you would like to add?

**Comment by blairanderson** [comment]
Wow! 

Sorry go ahead and close this issue!

Blair
