### ISSUE TITLE
Disable image selection

### ISSUE THREAD

**Issue by Aerijo** [atom/image-view#181]
### Description

Sometimes I drag the mouse cross the screen, and manage to highlight the whole image blue. 
Edit: Double clicking the zoom-to-fit or background colour buttons also does this.

This is mildly irritating and, as far as I can tell, it's impossible to copy anyway. I was going to make a PR to fix it, but wanted to see if there's a good reason to keep it first. Thoughts?

**Comment by 50Wliu** [comment]
I don't see a reason you should be able to select the image.
