### ISSUE TITLE
Display current zoom level

### ISSUE THREAD

**Issue by eboracus** [atom/image-view#37]
Would it be possible to add a display showing the current zoom level as a percentage and adding an ability to revert to 100%/default too. Once I'd zoomed I wasn't sure what was original size again. :/

I guess this is an area where this thread's idea: [Show zoom level (in status bar?) #4835](https://github.com/atom/atom/issues/4835) can be implemented.

**Comment by kand** [comment]
:+1: it's pretty annoying to accidentally change font size then have to shift back and forth through sizes again until I find where I was at.

**Comment by Ben3eeE** [comment]
@simurai was this closed by #40?

**Comment by simurai** [comment]
@Ben3eeE Partially. It shows the % when clicking the + or -, but not in "Zoom to fit" mode, then it just shows `auto`.

![zoom-](https://cloud.githubusercontent.com/assets/378023/9022045/40108c0a-389f-11e5-9d7d-6b909435d650.gif)

**Comment by eboracus** [comment]
Yes. Displaying it as `Auto (xy%)` when in `zoom to fit` would be great, if something like that is on the cards.

But that PR certainly resolved the primary issue nicely.

**Comment by damieng** [comment]
Closing this issue as the primary problem was solved by the PR and we don't have any plans to add a % zoom level next to the Auto mode.
