### ISSUE TITLE
Images with % in their URI do not load

### ISSUE THREAD

**Issue by tqn** [atom/image-view#38]
Let me begin by thanking you for the great editor! It's much better than any alternatives I've found.
I am using Atom 1.0.2 and Windows 8.1 x64.
When opening an image with `%` in its URI, it is not displayed properly, but can still be opened from the tree view. The dev tools report an `ERR_FILE_NOT_FOUND`.
![image](http://i.imgur.com/a4FM6tK.png)

Removing the `%`s seem to fix this issue.
![image](https://cloud.githubusercontent.com/assets/6508913/8817512/ab35bc3a-3066-11e5-87ad-1882c130ecf2.png)

**Comment by 50Wliu** [comment]
Does this happen in safe mode (`atom --safe`)?

**Comment by tqn** [comment]
Yes, and I seem to have a stack trace:
![image](https://cloud.githubusercontent.com/assets/6508913/8871206/243fa27e-3226-11e5-87a8-d2f2cfa1b82e.png)

**Comment by szhu** [comment]
Same with the `#` character: #42. Closing that issue because this one exists.

```shell
curl -L 'https://github.com/fluidicon.png' -o '#github.png'
atom '#github.png'
```

<img width="1086" alt="screen shot 2015-09-14 at 10 52 29 am" src="https://cloud.githubusercontent.com/assets/1570168/9857323/b61f286a-5ace-11e5-97b9-ad310b111588.png">

**Comment by Tyriar** [comment]
`%.jpg` loads just find for me, `%2F.jpg` and `#.png` don't.

**Comment by Tyriar** [comment]
It also happens with `?.jpg`.
