### ISSUE TITLE
Cmd + 9 for zoom to fit 

### ISSUE THREAD

**Issue by adius** [atom/image-view#41]
There are a lot of good things in the zoom to fit pull request https://github.com/atom/image-view/pull/40
which should be implemented.
A good start, however, would be to implement a simple zoom to fit shortcut with `cmd + 9` like its the default for preview

**Comment by simurai** [comment]
Yes. The `cmd + 9` keyboard shortcut will also be added as part of PR #40. Commit: https://github.com/atom/image-view/commit/47f34949d51acec8eec4814caba469e56676c4b4
