### ISSUE TITLE
Multiple {ImageEditor}s are created for every click on of the same file

### ISSUE THREAD

**Issue by wonderbeyond** [atom/image-view#48]
- Atome version: 1.2.2
- image-view version: 0.56.0

Note: I didn't see the issue at some previous version of `image-view`(sorry for not sure which version).

**Comment by wonderbeyond** [comment]
Additional Note: I only see this issue when my files names contain chinese chars:

![image](https://cloud.githubusercontent.com/assets/228361/11393734/5624811a-939c-11e5-8dd2-60c90ceed2ae.png)

**Comment by Ben3eeE** [comment]
I have the same issue except for every image file I open, not just Chinese character images. Reported a duplicate at https://github.com/atom/image-view/issues/52 look there for my repro steps.

**Comment by Ben3eeE** [comment]
My repro steps in #52 are with switching to another tab before opening the same image again. https://github.com/atom/atom/issues/12100 mentions that this is also reproducible by using pending pane items to open duplicate image tabs.
