### ISSUE TITLE
Image not loading from network folders

### ISSUE THREAD

**Issue by amurad** [atom/image-view#49]
When I click on an image in the folder tree, a tab with that image, but there is no image there except for a small box to select background color. tried on two different computers with atom 1.3-beta6.

UPDATE:
After further testing it appears, that its only an issue with network folders. Local folders load images fine. Since most of my development work is on VMs on network that I connect to from local computer running Windows 10, I did not pay attention to this aspect.

So it only works when project folder is local (like c:\temp) and not from network (like \\VM\temp

**Comment by 50Wliu** [comment]
Fixed by #54.
