### ISSUE TITLE
.bmp support

### ISSUE THREAD

**Issue by aovchinn** [atom/image-view#50]
I thought that bmp pictures should be visible as other formats, because why not?

**Comment by zhangzhimin** [comment]
imageExtensions = ['.gif', '.ico', '.jpeg', '.jpg', '.png', '.webp', 'bmp'], will it works?
is there other reason?

**Comment by jerone** [comment]
[**@zhangzhimin**](https://github.com/zhangzhimin) commented on [28 mei 2016 18:47 CEST](https://github.com/atom/image-view/issues/50#issuecomment-222317905 "2016-05-28T16:47:02Z - Replied by Github Reply Comments"):
> imageExtensions = ['.gif', '.ico', '.jpeg', '.jpg', '.png', '.webp', 'bmp'], will it works?  
> 
> is there other reason?

Accourding https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support is `.bmp` supported in Chromium.

**Comment by jerone** [comment]
Closed by https://github.com/atom/image-view/issues/56
