### ISSUE TITLE
Can open the same image multiple times

### ISSUE THREAD

**Issue by Ben3eeE** [atom/image-view#52]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

It is possible to open the same image multiple times, example: open image from tree-view, switch to other tab, open same image from tree-view and a new tab opens rather than switching to old tab.

@lee-dohm mentioned something about deduping logic being non-functional for this package.

### Steps to Reproduce

1. Open someimage.jpg from tree-view or fuzzy finder.
2. Switch to another tab
3. Open someimage.jpg from tree-view or fuzzy finder.
4. Observe you have 2 tabs open for someimage.jpg.

**Expected behavior:** Atom to switch to someimage.jpg tab opened in step 1 rather than opening new in step 3.

**Actual behavior:** Atom opens the someimage.jpg tab multiple times.

### Versions
1.6.X
Windows 7.

**Comment by Ben3eeE** [comment]
Oh I just found https://github.com/atom/image-view/issues/48 which seems to be the same issue. Except for me it happens with every file and not only with Chinese characters.

**Comment by lee-dohm** [comment]
Thanks for following up @Ben3eeE :grinning:
