### ISSUE TITLE
Option to set "zoom to fit" mode as default

### ISSUE THREAD

**Issue by zhangns** [atom/image-view#55]
It would be helpful if the user can set the image viewer to enable the "zoom to fit" mode **by default**.

PR #40 implements the "zoom to fit" mode, which is awesome, but the mode is apparently off by default. In some situations the user may want to quickly look through multiple images in a folder and may expect the image viewer to zoom each image to fit **by default**, so he does not need to toggle the "Zoom to fit" button **every time** a new image is opened.

**GIF showing current behavior**

![issue](https://cloud.githubusercontent.com/assets/10682831/15717937/b22eea1e-285b-11e6-94c3-0576d67d34d9.gif)

**Atom version:** 1.7.4
**image-view version:** 0.57.0
**OS:** Windows 8.1 64-bit

**Comment by simurai** [comment]
Ya, would be nice to have all controls in that bar remember their state. Maybe they all could be configs in the package settings.

**Comment by olee** [comment]
I really would like to see this as an option or even fixed default, too!
It is really annoying if you have high resolution images and want to click through many of them in the tree view.

**Comment by mnquintana** [comment]
Seems reasonable to just serialize the UI state in this case, instead of adding a whole slew of redundant config options.

**Comment by simurai** [comment]
> serialize the UI state

That would be great. Then it "remembers" also background and zoom level.

**Comment by olee** [comment]
Any update on this?

**Comment by lenovouser** [comment]
Would like to see this too!

**Comment by rysport** [comment]
Any update?

**Comment by dkoleary88** [comment]
I'd also love to see an improvement like this 👍

**Comment by fiso** [comment]
This would be a great addition. I found this thread while googling for a way to do this.

**Comment by LydiaF** [comment]
+1

**Comment by cbcoutinho** [comment]
Zoom to fit as a default would be fantastic

**Comment by riprop** [comment]
Please allow "Zoom to fit" as default or option configurable in properties,  it is really painful on HiDpi screens where picture appears frequently too small. Moreover turning it on and going to next image requires turning it on again ($#"%$%??? ). And for a slideshow - no way of using it  properly.

**Comment by mxmlnkn** [comment]
Why close this? This is a very reasonable option. I need this. IrfanView and many other have this.

**Comment by rsese** [comment]
It was closed because zoom to fit as default was implemented in https://github.com/atom/image-view/pull/81 as far as I can tell?  Looks like it's the default as of 1.20.

Unless you're asking why it's not an config option?
