### ISSUE TITLE
Zooming in does not always work and Zoom does not preserve aspect ratio

### ISSUE THREAD

**Issue by Ben3eeE** [atom/image-view#59]
### Prerequisites
- [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [X] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

If you zoom out too much you are unable to zoom back in until after resizing the Atom window. The zoom back in does not respect the original aspect ratio of the image.
### Steps to Reproduce
1. Open the `image-view` [spec image](https://github.com/atom/image-view/blob/master/spec/fixtures/binary-file.png) in Atom.
2. Zoom out a bunch of times, notice zoom gets stuck at some percentage, for me it was 23% or 15%.
3. (Try to) Zoom in a bunch of times, notice it works only once and then gets stuck, 23% to 38% or 15% to 25%.
4. Resize the Atom window.
5. Zoom in a bunch of times.

Added a gif of reproduction using the `image-view` [spec image](https://github.com/atom/image-view/blob/master/spec/fixtures/binary-file.png), which is 10x10. In this gif I press zoom in several times before resizing the Atom window and none of them work. After resizing the Atom window zoom in works but the image is no longer square.
![zoom2](https://cloud.githubusercontent.com/assets/1058982/16187931/58c02b38-36d3-11e6-8060-68d89b60149a.gif)

**Expected behavior:** Zooming in to work and aspect ratio to be preserved. Zooming to not be depending on the size of the Atom window.

**Actual behavior:** Zooming in does not work, if you resize the Atom window zoom in works but the aspect ratio of the image is wrong.
### Versions

Atom 1.8.0 on Windows 7
##### apm --version

```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 1.9.2.msysgit.0
visual studio`
```
##### atom --version

```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by Ben3eeE** [comment]
@thomasjo Should this be reopened until fixed so it doesn't get forgotten?

**Comment by thomasjo** [comment]
> @thomasjo Should this be reopened until fixed so it doesn't get forgotten?

Agreed!

**Comment by thomasjo** [comment]
Since it turns out this issue is not entirely resolved (see https://github.com/atom/image-view/pull/60#issuecomment-230218108), I'm reopening this issue.

**Comment by Ben3eeE** [comment]
I updated the original issue steps with what is described in https://github.com/atom/image-view/pull/60#issuecomment-230218108 to avoid confusion.
