### ISSUE TITLE
Support TIFF images

### ISSUE THREAD

**Issue by xhacker** [atom/image-view#61]

**Comment by xhacker** [comment]
Although it’s able to open TIFF images now, it’s not showing anything.
![2016-08-09 10 02 00](https://cloud.githubusercontent.com/assets/1051813/17542375/ea48181a-5e7c-11e6-8295-baf56a2328c5.png)

**Comment by JLCCI** [comment]
+1

**Comment by TimvdLippe** [comment]
While tiff is not supported in the browser, an option is to convert it into jpeg and show that instead. A library that can be used to do so is https://github.com/seikichi/tiff.js

**Comment by lee-dohm** [comment]
Thanks very much for the suggestion. Unfortunately, this isn't something that we want to take on maintaining long-term. We think this would be very appropriate for a community package, however.
