### ISSUE TITLE
Can't make a pending image view pane item permanent by double-clicking on the tab

### ISSUE THREAD

**Issue by lee-dohm** [atom/image-view#65]
The [standard methods](http://flight-manual.atom.io/using-atom/sections/pending-pane-items/) of making a pending pane item permanent are:

1. Double-clicking the tab of the file
1. Double-clicking the file in the tree view
1. Editing the contents of the file
1. Saving the file

Items 3 and 4 don't apply because Image View is read-only. Item 2 works, but not Item 1.

## Repro Steps

1. Launch Atom in your local Atom repository
1. Open the file `resources/app-icons/stable/png/1024.png` by single-clicking it in the Tree View
1. Double-click the tab for `1024.png`

**Expected:** Title of the tab to change from italics to non-italic signifying the transition of the pane item from pending to permanent
**Actual:** Title of the tab remains unchanged

**Comment by Ben3eeE** [comment]
I did some investigation into this and found the cause. https://github.com/Ben3eeE/image-view/tree/pending-pane-confirm but I am at a loss writing any specs for this. I just end up with more questions than answers whenever I try something.

**Comment by lee-dohm** [comment]
If [this code change](https://github.com/atom/image-view/compare/master...Ben3eeE:pending-pane-confirm) fixes the problem, then I would write the following tests:

1. When the Image View is the active pending item and `terminatePendingState` is called, ensure that  the `onDidTerminatePendingState` callback is called
1. When the Image View is *not* the active pending item and `terminatePendingState` is called, ensure that the `onDidTerminatePendingState` callback is *not* called

**Comment by Ben3eeE** [comment]
I have added the tests according to your recommendations I think. Everything is new I have no idea what I am doing :smile: 

PR is up and ready for review https://github.com/atom/image-view/issues/69
